fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(
                tauri_build::AppManifest::new()
                    .commands(&[
                        "load_track",
                        "preload_track",
                        "play",
                        "pause",
                        "stop",
                        "seek",
                        "set_volume",
                        "set_speed",
                        "set_pitch",
                        "set_eq",
                        "set_eq_bands",
                        "set_compressor",
                        "set_dual_compressor",
                        "set_regions",
                        "set_volume_envelope",
                        "get_playback_status",
                        "read_dir",
                        "get_waveform_slice",
                        "get_raw_samples",
                        "get_cloud_folders",
                        "open_file_external",
                        "read_audio_metadata",
                        "save_audio_metadata",
                        "read_file_bytes",
                        "read_file_binary",
                        "export_audio_file",
                        "save_playlist_file",
                        "load_playlist_file",
                        "broadcast_remote_state",
                        "list_midi_devices",
                        "connect_midi_device",
                        "scan_library_folder",
                        "check_files_exist",
                        "is_file_downloaded",
                        "move_file_to_trash",
                        "run_uvr_separation",
                        "list_audio_output_devices",
                        "get_current_audio_output_device",
                        "set_audio_output_device",
                        "stop_background_tracks"
                    ])

            )
    ).expect("failed to run tauri-build");
}
