fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(
                tauri_build::AppManifest::new()
                    .commands(&[
                        "load_track",
                        "preload_track",
                        "play",
                        "pause",
                        "stop",
                        "seek",
                        "set_volume",
                        "set_speed",
                        "set_pitch",
                        "set_eq",
                        "set_eq_bands",
                        "set_compressor",
                        "set_dual_compressor",
                        "set_regions",
                        "get_playback_status",
                        "read_dir",
                        "get_waveform_slice",
                        "get_raw_samples",
                        "get_cloud_folders",
                        "open_file_external",
                        "read_audio_metadata",
                        "save_audio_metadata",
                        "read_file_bytes"
                    ])
            )
    ).expect("failed to run tauri-build");
}
